name: gisb-test
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
        id: go

      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: go mod tidy && go build .

      - name: UnitTest
        run: go mod tidy && go test -v ./...

      - name: BenchmarkTest
        run: go mod tidy && go test -bench=. -benchtime=1s ./... -run=^$